CREATE TABLE IF NOT EXISTS note_tbl (
     id SERIAL PRIMARY KEY,
     title VARCHAR(250) NOT NULL,
     body TEXT NOT NULL,
     user_id INTEGER NOT NULL REFERENCES user_tbl(id),
     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);